"use client";
import { CalendarBlank, Check, Clock, Compass, MapPin, SpinnerGap } from "@phosphor-icons/react";
import { useMemo, useState } from "react";
import styles from "./BirthProfileForm.module.css";
type Props={tradition:"east"|"west"};
type BaziResponse={result:{engine:{version:string;calendarRange:string};effectiveLocalTime:string;trueSolarAdjustmentMinutes:number|null;pillars:Array<null|{key:string;label:string;ganZhi:string;stem:string;branch:string;hiddenStems:string[];fiveElements:string;naYin:string;stemTenGod:string;branchTenGods:string[]}>;solarTerms:{previous:string;previousAt:string;next:string;nextAt:string};rules:string[];warnings:string[]}};
const currentYear=new Date().getFullYear();
const years=Array.from({length:Math.min(currentYear,2100)-1899},(_,i)=>Math.min(currentYear,2100)-i);
const offsets=[-720,-660,-600,-540,-480,-420,-360,-300,-240,-180,-120,-60,0,60,120,180,210,240,270,300,330,345,360,390,420,480,540,570,600,660,720,780,840];
const formatOffset=(minutes:number)=>`UTC${minutes>=0?"+":"-"}${String(Math.floor(Math.abs(minutes)/60)).padStart(2,"0")}:${String(Math.abs(minutes)%60).padStart(2,"0")}`;
export function BirthProfileForm({tradition}:Props){
 const [year,setYear]=useState(1990),[month,setMonth]=useState(1),[day,setDay]=useState(1),[hour,setHour]=useState(12),[minute,setMinute]=useState(0); const [unknownTime,setUnknownTime]=useState(false),[place,setPlace]=useState(""),[utcOffsetMinutes,setUtcOffsetMinutes]=useState(480),[dayBoundary,setDayBoundary]=useState<"midnight"|"late-zi">("midnight"),[useTrueSolarTime,setUseTrueSolarTime]=useState(false),[longitude,setLongitude]=useState(""),[saved,setSaved]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(""),[bazi,setBazi]=useState<BaziResponse["result"]|null>(null); const maxDay=useMemo(()=>new Date(year,month,0).getDate(),[year,month]); const validDay=Math.min(day,maxDay);
 async function submit(e:React.FormEvent){e.preventDefault();setError("");setSaved(false);if(tradition==="west"){setSaved(true);return}setLoading(true);try{const response=await fetch("/api/bazi",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({year,month,day:validDay,hour:unknownTime?null:hour,minute:unknownTime?0:minute,utcOffsetMinutes,dayBoundary,useTrueSolarTime,longitude:useTrueSolarTime?Number(longitude):null})});const payload=await response.json() as BaziResponse&{error?:string};if(!response.ok)throw new Error(payload.error||"命盘计算失败");setBazi(payload.result);setSaved(true)}catch(reason){setError(reason instanceof Error?reason.message:"命盘计算失败")}finally{setLoading(false)}}
 return <><form className={`${styles.form} ${styles[tradition]}`} onSubmit={submit}>
  <div className={styles.notice}><CalendarBlank/><p><b>先建立出生资料</b><span>年份支持直接输入与长列表滚动；资料只用于排盘，你可以随时修改。</span></p></div>
  <fieldset><legend>出生日期 <em>必填</em></legend><div className={styles.dateGrid}>
   <label><span>年</span><input list="birth-years" inputMode="numeric" value={year} min={1900} max={currentYear} onChange={e=>setYear(Number(e.target.value))} aria-label="出生年份"/><datalist id="birth-years">{years.map(v=><option value={v} key={v}/>)}</datalist></label>
   <label><span>月</span><select value={month} onChange={e=>setMonth(Number(e.target.value))}>{Array.from({length:12},(_,i)=>i+1).map(v=><option value={v} key={v}>{v} 月</option>)}</select></label>
   <label><span>日</span><select value={validDay} onChange={e=>setDay(Number(e.target.value))}>{Array.from({length:maxDay},(_,i)=>i+1).map(v=><option value={v} key={v}>{v} 日</option>)}</select></label>
  </div><div className={styles.yearShortcuts}>{[1980,1990,2000,2010].map(v=><button type="button" onClick={()=>setYear(v)} key={v}>{v}年代</button>)}</div></fieldset>
  <fieldset><legend>出生时间 <em>建议填写</em></legend><div className={styles.timeRow}><Clock/><select value={hour} disabled={unknownTime} onChange={e=>setHour(Number(e.target.value))}>{Array.from({length:24},(_,i)=><option value={i} key={i}>{String(i).padStart(2,"0")} 时</option>)}</select><select value={minute} disabled={unknownTime} onChange={e=>setMinute(Number(e.target.value))}>{[0,15,30,45].map(i=><option value={i} key={i}>{String(i).padStart(2,"0")} 分</option>)}</select><label className={styles.unknown}><input type="checkbox" checked={unknownTime} onChange={e=>setUnknownTime(e.target.checked)}/>不知道具体时间</label></div><small>{tradition==="east"?"时辰会影响时柱；未知时将只生成不含时柱的有限命盘。":"出生时间影响上升点与宫位；未知时将不展示宫位结论。"}</small></fieldset>
  <fieldset><legend>出生地点与时区 <em>必填</em></legend><label className={styles.place}><MapPin/><input value={place} onChange={e=>setPlace(e.target.value)} placeholder="输入城市，例如：杭州 / New York"/><span>城市用于记录出生地；请按出生当日当地钟表选择 UTC 偏移。</span></label><label className={styles.fullLabel}><span>出生当日 UTC 偏移</span><select value={utcOffsetMinutes} onChange={e=>setUtcOffsetMinutes(Number(e.target.value))}>{offsets.map(value=><option value={value} key={value}>{formatOffset(value)}</option>)}</select></label></fieldset>
  {tradition==="east"&&<fieldset><legend>排盘口径 <em>可展开复核</em></legend><div className={styles.ruleGrid}><label><span>换日规则</span><select value={dayBoundary} onChange={e=>setDayBoundary(e.target.value as "midnight"|"late-zi")}><option value="midnight">午夜 00:00 换日</option><option value="late-zi">子初 23:00 换日</option></select></label><label className={styles.toggle}><input type="checkbox" checked={useTrueSolarTime} onChange={e=>setUseTrueSolarTime(e.target.checked)}/><Compass/>启用真太阳时校正</label></div>{useTrueSolarTime&&<label className={styles.fullLabel}><span>出生地经度（东经为正，西经为负）</span><input required type="number" step="0.01" min="-180" max="180" value={longitude} onChange={e=>setLongitude(e.target.value)} placeholder="例如：杭州 120.16"/><small>根据经度、时区中央经线与均时差校正；边界案例仍建议用专业历书复核。</small></label>}</fieldset>}
  <label className={styles.consent}><input required type="checkbox"/>我理解这是一种象征性自我探索工具，不替代医疗、法律或财务建议。</label>
  {error&&<p className={styles.error} role="alert">{error}</p>}
  <button className={styles.submit} disabled={!place.trim()||loading}>{loading?<><SpinnerGap className={styles.spin}/>正在确定排盘…</>:saved?<><Check/>重新计算命盘</>:tradition==="east"?"生成确定性命盘":"生成本命星盘"}</button>
 </form>{tradition==="east"&&bazi&&<BaziChart result={bazi}/>}</>;
}

function BaziChart({result}:{result:BaziResponse["result"]}){return <section className={styles.chart} aria-live="polite"><header><div><small>DETERMINISTIC CHART · 可复算盘面</small><h2>四柱命盘</h2></div><span>{result.engine.version}</span></header><div className={styles.pillars}>{result.pillars.map((pillar,index)=>pillar?<article key={pillar.key}><small>{pillar.label}</small><strong><i>{pillar.stem}</i><i>{pillar.branch}</i></strong><dl><div><dt>十神</dt><dd>{pillar.stemTenGod}</dd></div><div><dt>藏干</dt><dd>{pillar.hiddenStems.join(" · ")}</dd></div><div><dt>藏干十神</dt><dd>{pillar.branchTenGods.join(" · ")}</dd></div><div><dt>五行</dt><dd>{pillar.fiveElements}</dd></div><div><dt>纳音</dt><dd>{pillar.naYin}</dd></div></dl></article>:<article className={styles.emptyPillar} key={index}><small>时柱</small><strong>未知</strong><p>未使用推测时间</p></article>)}</div><div className={styles.evidence}><article><h3>计算时间</h3><p>{result.effectiveLocalTime}{result.trueSolarAdjustmentMinutes!==null&&`（真太阳时修正 ${result.trueSolarAdjustmentMinutes>=0?"+":""}${result.trueSolarAdjustmentMinutes} 分钟）`}</p><p>支持历法范围：{result.engine.calendarRange}</p></article><article><h3>相邻节气</h3><p>{result.solarTerms.previous} · {result.solarTerms.previousAt}</p><p>{result.solarTerms.next} · {result.solarTerms.nextAt}</p></article></div><details open><summary>排盘规则与边界</summary><ul>{result.rules.map(item=><li key={item}>{item}</li>)}</ul><ul className={styles.warnings}>{result.warnings.map(item=><li key={item}>{item}</li>)}</ul></details></section>}
