"use client";

import { Check, ChatCenteredText, ShieldCheck, Sparkle, X } from "@phosphor-icons/react";
import { useMemo, useState } from "react";
import { coachRehearsalReply, createRelationshipRehearsal, type RehearsalPath } from "@/lib/relationship-rehearsal";
import { createRelationshipLoop, getRelationshipCalibration, relationshipFollowupsEnabled, relationshipLoopInsight, reportRelationshipLoop, setRelationshipFollowupsEnabled, type PrivatePerson, type RelationshipLoop } from "@/lib/relationship-context";
import styles from "./RelationshipSandbox.module.css";

export function RelationshipSandbox({ person, onClose }: { person: PrivatePerson; onClose: () => void }) {
  const [situation, setSituation] = useState(""); const [need, setNeed] = useState(""); const [started, setStarted] = useState(false); const [path, setPath] = useState<RehearsalPath | null>(null); const [reply, setReply] = useState(""); const [loop, setLoop] = useState<RelationshipLoop | null>(null); const [outcome, setOutcome] = useState<RelationshipLoop["outcome"]>(); const [reflection, setReflection] = useState(""); const [reported, setReported] = useState<RelationshipLoop | null>(null); const [followups, setFollowups] = useState(() => relationshipFollowupsEnabled());
  const calibration = useMemo(() => getRelationshipCalibration(person.id), [person.id, reported]);
  const rehearsal = useMemo(() => createRelationshipRehearsal(person, situation, need, calibration), [person, situation, need, calibration]);
  const report = (actionTaken: boolean) => { if (!loop) return; const result = reportRelationshipLoop(loop.id, { actionTaken, outcome, reflection }); if (result) setReported(result); };
  return <div className={styles.backdrop} role="dialog" aria-modal="true" aria-labelledby="sandbox-title"><section className={styles.sheet}>
    <header><span><Sparkle /> RELATIONSHIP SANDBOX</span><button onClick={onClose} aria-label="关闭关系演练"><X /></button></header><h2 id="sandbox-title">和 {person.displayName} 练习怎么说</h2><p className={styles.intro}>这是一次私密的沟通排练，不是 {person.displayName} 的数字分身。所有“回应”都只是依据你目前资料给出的可能路径。</p>
    {!started ? <form onSubmit={(event) => { event.preventDefault(); setStarted(true); }} className={styles.setup}><label>这次想谈什么？<textarea autoFocus required maxLength={180} value={situation} onChange={(event) => setSituation(event.target.value)} /></label><label>你希望这次谈话带来什么？<textarea maxLength={180} value={need} onChange={(event) => setNeed(event.target.value)} /></label><button type="submit"><ChatCenteredText />开始演练</button></form> : reported ? <div className={styles.rehearsal}><div className={styles.provenance}><ShieldCheck />现实反馈已记录：它只代表这次互动，不会变成对 TA 的人格结论。</div><article className={styles.opening}><small>拾光已校准一点点</small><p>{relationshipLoopInsight(reported)}</p></article><button className={styles.primary} onClick={onClose}>回到我的关系</button></div> : <div className={styles.rehearsal}>
      <div className={styles.provenance}><ShieldCheck />{rehearsal.perspective}</div>{rehearsal.calibration && <article className={styles.opening}><small>来自你记录过的现实反馈</small><p>{rehearsal.calibration.summary}</p><span>{rehearsal.calibration.nextPractice}</span></article>}<article className={styles.opening}><small>你可以这样开场</small><p>“{rehearsal.opening}”</p></article><div className={styles.checkpoints}><b>说之前，先过这三关</b><ul>{rehearsal.checkpoints.map((item) => <li key={item}><Check />{item}</li>)}</ul></div><div className={styles.paths}><b>如果 TA 这样回应……</b>{rehearsal.paths.map((item) => <button type="button" key={item.id} className={path?.id === item.id ? styles.activePath : ""} onClick={() => setPath(item)}><strong>{item.label}</strong><span>{item.response}</span></button>)}</div>{path && <article className={styles.nextMove}><small>你可以接着说</small><p>“{path.nextMove}”</p></article>}<label className={styles.reply}>换成你的话试一句<textarea maxLength={240} value={reply} onChange={(event) => setReply(event.target.value)} /></label><p className={styles.coach}><Sparkle />{coachRehearsalReply(reply)}</p>
      {!loop ? <button className={styles.primary} type="button" onClick={() => setLoop(createRelationshipLoop({ personId: person.id, situation, need }))}>去和 TA 聊，回来告诉我结果</button> : <section className={styles.followup}><b>这次真的去聊了吗？</b><p>一句话或点一下就够。你的反馈会让下一次演练更贴近现实。</p><label><input type="checkbox" checked={followups} onChange={(event) => { setFollowups(event.target.checked); setRelationshipFollowupsEnabled(event.target.checked); }} /> 下次打开 LifeMirror 时提醒我回来复盘</label><div>{([['smooth','顺利'],['mixed','一般'],['rough','翻车']] as const).map(([value,label]) => <button type="button" className={outcome === value ? styles.activeOutcome : ""} key={value} onClick={() => setOutcome(value)}>{label}</button>)}</div><textarea maxLength={300} value={reflection} onChange={(event) => setReflection(event.target.value)} placeholder="可选：TA 怎么回应？你有什么感受？" /><button className={styles.primary} type="button" onClick={() => report(Boolean(outcome))}>记录这次现实反馈</button><button className={styles.skip} type="button" onClick={() => report(false)}>这次还没开口</button></section>}
      <p className={styles.temporary}>只有你主动记录的现实进展才会留下；它只代表这次互动，不会自动写成对 TA 的事实。</p>
    </div>}
  </section></div>;
}
